//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/compute_instance_common_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/compute_instance_common_type.proto.
 */
export const file_osac_private_v1_compute_instance_common_type: GenFile = /*@__PURE__*/
  fileDesc("CjJvc2FjL3ByaXZhdGUvdjEvY29tcHV0ZV9pbnN0YW5jZV9jb21tb25fdHlwZS5wcm90bxIPb3NhYy5wcml2YXRlLnYxIj8KFENvbXB1dGVJbnN0YW5jZUltYWdlEhMKC3NvdXJjZV90eXBlGAEgASgJEhIKCnNvdXJjZV9yZWYYAiABKAkiJwoTQ29tcHV0ZUluc3RhbmNlRGlzaxIQCghzaXplX2dpYhgBIAEoBWIGcHJvdG8z");

/**
 * Contains the image configuration for a compute instance.
 *
 * @generated from message osac.private.v1.ComputeInstanceImage
 */
export type ComputeInstanceImage = Message<"osac.private.v1.ComputeInstanceImage"> & {
  /**
   * Image source type (e.g. "registry").
   *
   * @generated from field: string source_type = 1;
   */
  sourceType: string;

  /**
   * Image reference (e.g. OCI image URL).
   *
   * @generated from field: string source_ref = 2;
   */
  sourceRef: string;
};

/**
 * Describes the message osac.private.v1.ComputeInstanceImage.
 * Use `create(ComputeInstanceImageSchema)` to create a new message.
 */
export const ComputeInstanceImageSchema: GenMessage<ComputeInstanceImage> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_compute_instance_common_type, 0);

/**
 * Contains the disk configuration for a compute instance.
 *
 * @generated from message osac.private.v1.ComputeInstanceDisk
 */
export type ComputeInstanceDisk = Message<"osac.private.v1.ComputeInstanceDisk"> & {
  /**
   * Disk size in GiB.
   *
   * @generated from field: int32 size_gib = 1;
   */
  sizeGib: number;
};

/**
 * Describes the message osac.private.v1.ComputeInstanceDisk.
 * Use `create(ComputeInstanceDiskSchema)` to create a new message.
 */
export const ComputeInstanceDiskSchema: GenMessage<ComputeInstanceDisk> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_compute_instance_common_type, 1);

