//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/compute_instance_common_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/compute_instance_common_type.proto.
 */
export const file_osac_public_v1_compute_instance_common_type: GenFile = /*@__PURE__*/
  fileDesc("CjFvc2FjL3B1YmxpYy92MS9jb21wdXRlX2luc3RhbmNlX2NvbW1vbl90eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSI/ChRDb21wdXRlSW5zdGFuY2VJbWFnZRITCgtzb3VyY2VfdHlwZRgBIAEoCRISCgpzb3VyY2VfcmVmGAIgASgJIlMKE0NvbXB1dGVJbnN0YW5jZURpc2sSEAoIc2l6ZV9naWIYASABKAUSGQoMc3RvcmFnZV90aWVyGAIgASgJSACIAQFCDwoNX3N0b3JhZ2VfdGllcmIGcHJvdG8z");

/**
 * Contains the image configuration for a compute instance.
 *
 * @generated from message osac.public.v1.ComputeInstanceImage
 */
export type ComputeInstanceImage = Message<"osac.public.v1.ComputeInstanceImage"> & {
  /**
   * Image source type (e.g. "registry").
   *
   * @generated from field: string source_type = 1;
   */
  sourceType: string;

  /**
   * Image reference (e.g. OCI image URL).
   *
   * @generated from field: string source_ref = 2;
   */
  sourceRef: string;
};

/**
 * Describes the message osac.public.v1.ComputeInstanceImage.
 * Use `create(ComputeInstanceImageSchema)` to create a new message.
 */
export const ComputeInstanceImageSchema: GenMessage<ComputeInstanceImage> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_compute_instance_common_type, 0);

/**
 * Contains the disk configuration for a compute instance.
 *
 * @generated from message osac.public.v1.ComputeInstanceDisk
 */
export type ComputeInstanceDisk = Message<"osac.public.v1.ComputeInstanceDisk"> & {
  /**
   * Disk size in GiB.
   *
   * @generated from field: int32 size_gib = 1;
   */
  sizeGib: number;

  /**
   * Storage tier name (e.g., "standard", "fast", "archive").
   *
   * @generated from field: optional string storage_tier = 2;
   */
  storageTier?: string | undefined;
};

/**
 * Describes the message osac.public.v1.ComputeInstanceDisk.
 * Use `create(ComputeInstanceDiskSchema)` to create a new message.
 */
export const ComputeInstanceDiskSchema: GenMessage<ComputeInstanceDisk> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_compute_instance_common_type, 1);

