//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/storage_tier_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/storage_tier_type.proto.
 */
export const file_osac_public_v1_storage_tier_type: GenFile = /*@__PURE__*/
  fileDesc("CiZvc2FjL3B1YmxpYy92MS9zdG9yYWdlX3RpZXJfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEirwEKC1N0b3JhZ2VUaWVyEgoKAmlkGAEgASgJEioKCG1ldGFkYXRhGAIgASgLMhgub3NhYy5wdWJsaWMudjEuTWV0YWRhdGESNQoEc3BlYxgDIAEoCzIfLm9zYWMucHVibGljLnYxLlN0b3JhZ2VUaWVyU3BlY0IGukgDyAEBEjEKBnN0YXR1cxgEIAEoCzIhLm9zYWMucHVibGljLnYxLlN0b3JhZ2VUaWVyU3RhdHVzItMBCg9TdG9yYWdlVGllclNwZWMSEwoLZGVzY3JpcHRpb24YASABKAkSPQoIcHJvdG9jb2wYAiABKA4yHy5vc2FjLnB1YmxpYy52MS5TdG9yYWdlUHJvdG9jb2xCCrpIB4IBBBABIAASHgoWbWF4X3JlYWRfYmFuZHdpZHRoX21icxgDIAEoBRIfChdtYXhfd3JpdGVfYmFuZHdpZHRoX21icxgEIAEoBRIaChJlbmNyeXB0aW9uX2VuYWJsZWQYBiABKAhKBAgFEAZSCXF1b3RhX2dpYiJmChFTdG9yYWdlVGllclN0YXR1cxIvCgVzdGF0ZRgBIAEoDjIgLm9zYWMucHVibGljLnYxLlN0b3JhZ2VUaWVyU3RhdGUSFAoHbWVzc2FnZRgCIAEoCUgAiAEBQgoKCF9tZXNzYWdlKmkKD1N0b3JhZ2VQcm90b2NvbBIgChxTVE9SQUdFX1BST1RPQ09MX1VOU1BFQ0lGSUVEEAASGAoUU1RPUkFHRV9QUk9UT0NPTF9ORlMQARIaChZTVE9SQUdFX1BST1RPQ09MX0JMT0NLEAIqVQoQU3RvcmFnZVRpZXJTdGF0ZRIiCh5TVE9SQUdFX1RJRVJfU1RBVEVfVU5TUEVDSUZJRUQQABIdChlTVE9SQUdFX1RJRVJfU1RBVEVfQUNUSVZFEAFiBnByb3RvMw", [file_buf_validate_validate, file_osac_public_v1_metadata_type]);

/**
 * Describes a class of storage service that can be referenced by name when provisioning
 * storage-enabled resources.
 *
 * StorageTiers are admin-managed catalog resources. Tenant users select a tier by name instead of
 * specifying raw storage backend details. Cloud Provider Admins control the available tiers through
 * the private API.
 *
 * The `spec` contains the tier's advertised service level. The `status` contains the current state
 * of the storage tier, is provided by the system and can't be modified by the user.
 *
 * @generated from message osac.public.v1.StorageTier
 */
export type StorageTier = Message<"osac.public.v1.StorageTier"> & {
  /**
   * Unique identifier of the storage tier.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the storage tier.
   *
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Advertised service level of the storage tier.
   *
   * @generated from field: osac.public.v1.StorageTierSpec spec = 3;
   */
  spec?: StorageTierSpec | undefined;

  /**
   * Current operational status of the storage tier.
   *
   * @generated from field: osac.public.v1.StorageTierStatus status = 4;
   */
  status?: StorageTierStatus | undefined;
};

/**
 * Describes the message osac.public.v1.StorageTier.
 * Use `create(StorageTierSchema)` to create a new message.
 */
export const StorageTierSchema: GenMessage<StorageTier> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_storage_tier_type, 0);

/**
 * Defines the advertised service level of a StorageTier.
 *
 * @generated from message osac.public.v1.StorageTierSpec
 */
export type StorageTierSpec = Message<"osac.public.v1.StorageTierSpec"> & {
  /**
   * Human-readable description of the storage tier.
   *
   * @generated from field: string description = 1;
   */
  description: string;

  /**
   * Storage protocol used by this tier. Always an explicit protocol (NFS or BLOCK); never UNSPECIFIED.
   *
   * @generated from field: osac.public.v1.StorageProtocol protocol = 2;
   */
  protocol: StorageProtocol;

  /**
   * Maximum read bandwidth in megabytes per second.
   *
   * @generated from field: int32 max_read_bandwidth_mbs = 3;
   */
  maxReadBandwidthMbs: number;

  /**
   * Maximum write bandwidth in megabytes per second.
   *
   * @generated from field: int32 max_write_bandwidth_mbs = 4;
   */
  maxWriteBandwidthMbs: number;

  /**
   * Whether data at rest is encrypted on this tier.
   *
   * @generated from field: bool encryption_enabled = 6;
   */
  encryptionEnabled: boolean;
};

/**
 * Describes the message osac.public.v1.StorageTierSpec.
 * Use `create(StorageTierSpecSchema)` to create a new message.
 */
export const StorageTierSpecSchema: GenMessage<StorageTierSpec> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_storage_tier_type, 1);

/**
 * Contains the system-provided status of a StorageTier.
 *
 * @generated from message osac.public.v1.StorageTierStatus
 */
export type StorageTierStatus = Message<"osac.public.v1.StorageTierStatus"> & {
  /**
   * Current lifecycle state of the storage tier.
   *
   * @generated from field: osac.public.v1.StorageTierState state = 1;
   */
  state: StorageTierState;

  /**
   * Human-readable message providing additional details about the current state.
   *
   * @generated from field: optional string message = 2;
   */
  message?: string | undefined;
};

/**
 * Describes the message osac.public.v1.StorageTierStatus.
 * Use `create(StorageTierStatusSchema)` to create a new message.
 */
export const StorageTierStatusSchema: GenMessage<StorageTierStatus> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_storage_tier_type, 2);

/**
 * Identifies the storage protocol used by a storage tier.
 *
 * @generated from enum osac.public.v1.StorageProtocol
 */
export enum StorageProtocol {
  /**
   * Protocol is unknown or has not been specified.
   *
   * @generated from enum value: STORAGE_PROTOCOL_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * NFS (Network File System) protocol for file-based storage access.
   *
   * @generated from enum value: STORAGE_PROTOCOL_NFS = 1;
   */
  NFS = 1,

  /**
   * Block storage protocol for volume-based storage access.
   *
   * @generated from enum value: STORAGE_PROTOCOL_BLOCK = 2;
   */
  BLOCK = 2,
}

/**
 * Describes the enum osac.public.v1.StorageProtocol.
 */
export const StorageProtocolSchema: GenEnum<StorageProtocol> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_storage_tier_type, 0);

/**
 * Lifecycle states for StorageTier resources.
 *
 * @generated from enum osac.public.v1.StorageTierState
 */
export enum StorageTierState {
  /**
   * State is unknown or has not been determined yet.
   *
   * @generated from enum value: STORAGE_TIER_STATE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * The storage tier is active and available for use by tenants.
   *
   * @generated from enum value: STORAGE_TIER_STATE_ACTIVE = 1;
   */
  ACTIVE = 1,
}

/**
 * Describes the enum osac.public.v1.StorageTierState.
 */
export const StorageTierStateSchema: GenEnum<StorageTierState> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_storage_tier_type, 1);

